### ISSUE TITLE
Implement more progressive fog of war.

### ISSUE THREAD

**Issue by agjlewis** [mattconsto/gamejam#24]
I had a thought about how to make the FOW slightly smoother when walking around.

**Comment by agjlewis** [comment]
Done, if its not liked there is a boolean flag to disable it. Given the flexibility of the FoW system that was implemented I thought this might be a nice way to remove what feels like judder when walking around.

**Comment by agjlewis** [comment]
What do other people think of it ? (Parameter could be tweaked)

**Comment by mikejewell** [comment]
Oo, that is nice! Is it possible to try it with a larger 'circle' around the player at 100% visibility, which then tails off to 0% in 2 or 3 squares?
